[package]
name = "pigeonhole-cli"
description = "phdb: command-line shell and tools for Pigeonhole databases."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[[bin]]
name = "phdb"
path = "src/main.rs"

[dependencies]
pigeonhole = { workspace = true }

[lints]
workspace = true
