[package]
name = "pigeonhole-arrow"
description = "Arrow RecordBatch export for Pigeonhole scans."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
pigeonhole = { workspace = true }

[lints]
workspace = true
